### ISSUE TITLE
Node shutdown panic (Index 2769)

### ISSUE THREAD

**Issue by Phyloiota** [iotaledger/goshimmer#1138]
## Bug description
Node was online over 10 hours after fresh installation with v0.5.3
did fall one time out of sync for about 30 minutes after 10 hours running nicely, but resynched automatically
maybe 1 hour later:
dashboard not accessible, node seems to be offline, checked hetzner - vps - thats online and normal , accessed root  - node in restarting loop:
    FATAL   Database        database/plugin.go:94  The database is marked as not properly shutdown/corrupted, please delete the database folder and restart.
Opened logfile of the last 2 hours :
Shutdown reason seems this: 
  INFO    Gossip  gossip/plugin.go:118    Neighbor added: 135.181.82.55:14666 / XUKsweqmPfc
panic: Index(2769) is smaller than the lowest known Index

updated and restarted with
cd /opt/goshimmer && docker-compose down && rm db/* && docker-compose pull && docker-compose up -d

synced fast, all running fine again

## GoShimmer version

0.5.3

## Hardware specification

CPX21

3VCPU
4 GB RAM
80 GB SSD

Error log of last 2 hours:

[panic index 2769 node.txt](https://github.com/iotaledger/goshimmer/files/6211832/panic.index.2769.node.txt)

**Comment by Phyloiota** [comment]
as the node did not sync and cpu was running on max i stopped goshimmer and tried restart, there i got the error again
The database is marked as not properly shutdown/corrupted, please delete the data .
error log of last 2 hours here:
[after node restart and not sync.txt](https://github.com/iotaledger/goshimmer/files/6212070/after.node.restart.and.not.sync.txt)

**Comment by JanOonk** [comment]
Once the database is corrupted, the only fix is to remove the database data.

Btw: I got this panic error by sending 3 transactions almost parallel (less than 1sec), all from Wallet A to Wallet B by using 3 shells/cmd.exe and running `cli-wallet.exe send-funds -amount 1 -dest-addr WalletB`.

Attached my log. At **2021-03-25 18:10:07** the panic error.
[errorlog.zip](https://github.com/iotaledger/goshimmer/files/6212330/errorlog.zip)

**Comment by mstrewe** [comment]
I got the panic when i receive from faucet:

```
panic: Index(2746) is smaller than the lowest known Index

goroutine 57 [running]:
github.com/iotaledger/goshimmer/packages/markers.(*ParentReferences).HighestReferencedMarkers(0xc017771ec0, 0xaba, 0xc016558240)
        /root/goshimmer/packages/markers/parent_references.go:160 +0x29f
github.com/iotaledger/goshimmer/packages/markers.(*Sequence).HighestReferencedParentMarkers(...)
        /root/goshimmer/packages/markers/sequence.go:107
github.com/iotaledger/goshimmer/packages/markers.(*Manager).markersReferenceMarkers.func1.1.1(0xc01c48f270)
        /root/goshimmer/packages/markers/manager.go:366 +0x57
github.com/iotaledger/goshimmer/packages/markers.(*CachedSequence).Consume.func1(0x1d64258, 0xc01c48f270)
        /root/goshimmer/packages/markers/sequence.go:230 +0x42
github.com/iotaledger/hive.go/objectstorage.(*CachedObjectImpl).Consume(0xc01356b220, 0xc01ddf9ad0, 0x0, 0x0, 0x0, 0xc016558100)
        /root/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20210317185122-1ac328c4054f/objectstorage/cached_object.go:132 +0xda
github.com/iotaledger/goshimmer/packages/markers.(*CachedSequence).Consume(0xc018672ce0, 0xc0165581e0, 0x0, 0x0, 0x0, 0xc01356b220)
        /root/goshimmer/packages/markers/sequence.go:229 +0x8b
github.com/iotaledger/goshimmer/packages/markers.(*Manager).markersReferenceMarkers.func1.1(0x6, 0xaba, 0xc018672d01)
        /root/goshimmer/packages/markers/manager.go:365 +0xe8
github.com/iotaledger/goshimmer/packages/markers.(*Markers).ForEach(0xc017771c80, 0xc018672df8, 0xc017771401)
        /root/goshimmer/packages/markers/marker.go:262 +0x110
github.com/iotaledger/goshimmer/packages/markers.(*Manager).markersReferenceMarkers.func1(0xc017771c80, 0xc012964a01, 0xc018672e00)
        /root/goshimmer/packages/markers/manager.go:364 +0x13d
github.com/iotaledger/goshimmer/packages/markers.(*Manager).markersReferenceMarkers(0xc000116fc0, 0xc017771c80, 0xc017771410, 0x1, 0x0)
        /root/goshimmer/packages/markers/manager.go:377 +0x12b
github.com/iotaledger/goshimmer/packages/markers.(*Manager).IsInPastCone(0xc000116fc0, 0xc017771bc0, 0xc0177713b0, 0x0)
        /root/goshimmer/packages/markers/manager.go:225 +0x1c5
github.com/iotaledger/goshimmer/packages/tangle.(*Utils).messageStronglyApprovedBy(0xc0000b8c58, 0x5a49c2504f48ac9e, 0x1e0a4a72b1e6c52b, 0xe8af4dc71a6176b3, 0x176d290130e27f70, 0xd06627a1a892cc4c, 0x20ff61b697fe2366, 0x550e17fde422eddf, 0x7d92e2398cde45e5, 0xc00d9f9100)
        /root/goshimmer/packages/tangle/utils.go:215 +0x305
github.com/iotaledger/goshimmer/packages/tangle.(*Utils).MessageApprovedBy(0xc0000b8c58, 0x5a49c2504f48ac9e, 0x1e0a4a72b1e6c52b, 0xe8af4dc71a6176b3, 0x176d290130e27f70, 0xd06627a1a892cc4c, 0x20ff61b697fe2366, 0x550e17fde422eddf, 0x7d92e2398cde45e5, 0xc00d9f8f00)  
        /root/goshimmer/packages/tangle/utils.go:153 +0xa7
github.com/iotaledger/goshimmer/packages/tangle.(*Utils).TransactionApprovedByMessage.func2(0xc028782780)
        /root/goshimmer/packages/tangle/utils.go:135 +0x1f9
github.com/iotaledger/goshimmer/packages/tangle.(*CachedMessage).Consume.func1(0x1d64438, 0xc028782780)
        /root/goshimmer/packages/tangle/message.go:601 +0x42
github.com/iotaledger/hive.go/objectstorage.(*CachedObjectImpl).Consume(0xc01356a820, 0xc01ddf96e0, 0x0, 0x0, 0x0, 0xc007c02900)
        /root/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20210317185122-1ac328c4054f/objectstorage/cached_object.go:132 +0xda
github.com/iotaledger/goshimmer/packages/tangle.(*CachedMessage).Consume(0xc018673440, 0xc007c029a0, 0x20)
        /root/goshimmer/packages/tangle/message.go:600 +0x7e
github.com/iotaledger/goshimmer/packages/tangle.(*Utils).TransactionApprovedByMessage(0xc0000b8c58, 0x86138e9268e5e93d, 0x5994723710192687, 0xc4822355185c3da7, 0x3a65937676da4115, 0xd2a55d6173d0f3ad, 0x4c01f905adff2ec2, 0xd592988acfcd9c70, 0x3cad03a206d2a14e, 0xc018673580)
        /root/goshimmer/packages/tangle/utils.go:125 +0x365
github.com/iotaledger/goshimmer/packages/tangle.(*Utils).AllTransactionsApprovedByMessages(0xc0000b8c58, 0xc017771aa0, 0xc0186737ae, 0x1, 0x1, 0x3cad03a206d2a14e)
        /root/goshimmer/packages/tangle/utils.go:100 +0xe7
github.com/iotaledger/goshimmer/packages/tangle.(*Booker).Book.func1.1(0xc000209e00)
        /root/goshimmer/packages/tangle/booker.go:98 +0x1ef
github.com/iotaledger/goshimmer/packages/tangle.(*CachedMessageMetadata).Consume.func1(0x1d64498, 0xc000209e00)
        /root/goshimmer/packages/tangle/message.go:1051 +0x42
github.com/iotaledger/hive.go/objectstorage.(*CachedObjectImpl).Consume(0xc01356a780, 0xc01ddf91c0, 0x0, 0x0, 0x0, 0xc0144aa800)
        /root/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20210317185122-1ac328c4054f/objectstorage/cached_object.go:132 +0xda
github.com/iotaledger/goshimmer/packages/tangle.(*CachedMessageMetadata).Consume(0xc01ddf91b0, 0xc0144aa8c0, 0x0, 0x0, 0x0, 0x0)
        /root/goshimmer/packages/tangle/message.go:1050 +0x8b
github.com/iotaledger/goshimmer/packages/tangle.(*Booker).Book.func1(0xc028782780)
        /root/goshimmer/packages/tangle/booker.go:89 +0x12a
github.com/iotaledger/goshimmer/packages/tangle.(*CachedMessage).Consume.func1(0x1d64438, 0xc028782780)
        /root/goshimmer/packages/tangle/message.go:601 +0x42
github.com/iotaledger/hive.go/objectstorage.(*CachedObjectImpl).Consume(0xc01356a820, 0xc01ddf91a0, 0x0, 0x0, 0x0, 0xc0144aa800)
        /root/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20210317185122-1ac328c4054f/objectstorage/cached_object.go:132 +0xda
github.com/iotaledger/goshimmer/packages/tangle.(*CachedMessage).Consume(0xc018673bd8, 0xc0144aa880, 0x20)
        /root/goshimmer/packages/tangle/message.go:600 +0x7e
github.com/iotaledger/goshimmer/packages/tangle.(*Booker).Book(0xc00007d4a0, 0xd2a55d6173d0f3ad, 0x4c01f905adff2ec2, 0xd592988acfcd9c70, 0x3cad03a206d2a14e, 0x410fda, 0x12f7dc0)
        /root/goshimmer/packages/tangle/booker.go:88 +0x116
github.com/iotaledger/goshimmer/packages/tangle.(*Booker).Setup.func1(0xd2a55d6173d0f3ad, 0x4c01f905adff2ec2, 0xd592988acfcd9c70, 0x3cad03a206d2a14e)
        /root/goshimmer/packages/tangle/booker.go:60 +0x47
github.com/iotaledger/goshimmer/packages/tangle.MessageIDCaller(0x125a8a0, 0xc000414640, 0xc01ddf9140, 0x1, 0x1)
        /root/goshimmer/packages/tangle/tangle.go:179 +0x93
github.com/iotaledger/hive.go/events.(*Event).Trigger(0xc000411aa0, 0xc01ddf9140, 0x1, 0x1)
        /root/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20210317185122-1ac328c4054f/events/event.go:32 +0x10b
github.com/iotaledger/goshimmer/packages/tangle.(*Scheduler).scheduleMessage.func1(0xc000209e00)
        /root/goshimmer/packages/tangle/scheduler.go:106 +0x169
github.com/iotaledger/goshimmer/packages/tangle.(*CachedMessageMetadata).Consume.func1(0x1d64498, 0xc000209e00)
        /root/goshimmer/packages/tangle/message.go:1051 +0x42
github.com/iotaledger/hive.go/objectstorage.(*CachedObjectImpl).Consume(0xc01356a780, 0xc01ddf9130, 0x0, 0x0, 0x0, 0xc017771800)
        /root/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20210317185122-1ac328c4054f/objectstorage/cached_object.go:132 +0xda
github.com/iotaledger/goshimmer/packages/tangle.(*CachedMessageMetadata).Consume(0xc01ddf9120, 0xc017771860, 0x0, 0x0, 0x0, 0x0)
        /root/goshimmer/packages/tangle/message.go:1050 +0x8b
github.com/iotaledger/goshimmer/packages/tangle.(*Scheduler).scheduleMessage(0xc00010bb00, 0xd2a55d6173d0f3ad, 0x4c01f905adff2ec2, 0xd592988acfcd9c70, 0x3cad03a206d2a14e)
        /root/goshimmer/packages/tangle/scheduler.go:101 +0xfc
github.com/iotaledger/goshimmer/packages/tangle.(*Scheduler).run.func1(0xc00010bb00)
        /root/goshimmer/packages/tangle/scheduler.go:86 +0x165
created by github.com/iotaledger/goshimmer/packages/tangle.(*Scheduler).run
        /root/goshimmer/packages/tangle/scheduler.go:80 +0x5c
```

**Comment by jonastheis** [comment]
This was fixed with https://github.com/iotaledger/goshimmer/pull/1140 and https://github.com/iotaledger/goshimmer/pull/1146
