### ISSUE TITLE
Panic on devnet and pre-devnet

### ISSUE THREAD

**Issue by georgysavva** [iotaledger/goshimmer#1936]
Some of our Goshimmer nodes are down on pre-devnet and devnet for several days due to a panic. See the logs below:
```
2021-12-06T19:30:15+01:00	INFO	Gossip	node/plugin.go:101	Neighbor removed: 162.55.178.233:14666 / 9zehsgsTfSm
2021-12-06T19:30:15+01:00	INFO	Gossip	gossip/manager.go:279	Connection established	{"id": "EcgfU8U39HL", "localAddr": "/ip4/172.25.0.2/tcp/14666", "remoteAddr": "/ip4/195.90.214.136/tcp/14666"}
2021-12-06T19:30:15+01:00	INFO	Gossip	node/plugin.go:101	Neighbor added: 195.90.214.136:14666 / EcgfU8U39HL
echo: http: panic serving 172.25.0.1:40040: runtime error: invalid memory address or nil pointer dereference
goroutine 715914 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1801 +0xb9
panic({0x176ee20, 0x2d53230})
	/usr/local/go/src/runtime/panic.go:1047 +0x266
github.com/iotaledger/goshimmer/packages/ledgerstate.(*Transaction).Essence(...)
	/goshimmer/packages/ledgerstate/transaction.go:348
github.com/iotaledger/goshimmer/packages/tangle.(*LedgerState).SnapshotUTXO(0xc0003ffcb0)
	/goshimmer/packages/tangle/ledgerstate.go:207 +0x43e
github.com/iotaledger/goshimmer/plugins/webapi/snapshot.DumpCurrentLedger({0x230fed8, 0xc04dcc40e0})
	/goshimmer/plugins/webapi/snapshot/plugin.go:52 +0x50
github.com/labstack/echo.(*Echo).Add.func1({0x230fed8, 0xc04dcc40e0})
	/go/pkg/mod/github.com/labstack/echo@v3.3.10+incompatible/echo.go:490 +0x6d
github.com/labstack/echo/middleware.CORSWithConfig.func1.1({0x230fed8, 0xc04dcc40e0})
	/go/pkg/mod/github.com/labstack/echo@v3.3.10+incompatible/middleware/cors.go:117 +0x578
github.com/labstack/echo.(*Echo).ServeHTTP(0xc00041c000, {0x22c04c8, 0xc00042e460}, 0xc000603100)
	/go/pkg/mod/github.com/labstack/echo@v3.3.10+incompatible/echo.go:593 +0x2ea
net/http.serverHandler.ServeHTTP({0xc00ac072c0}, {0x22c04c8, 0xc00042e460}, 0xc000603100)
	/usr/local/go/src/net/http/server.go:2878 +0x43b
net/http.(*conn).serve(0xc006658000, {0x22d2c78, 0xc00e460660})
	/usr/local/go/src/net/http/server.go:1929 +0xb08
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3033 +0x4e8
2021-12-06T19:30:34+01:00	INFO	AutoPeering	autopeering/plugin.go:145	Removed offline: 49.12.199.218:14646 / GaozK6MSyCA
2021-12-06T19:30:47+01:00	INFO	AutoPeering	autopeering/plugin.go:145	Removed offline: 167.86.122.61:14646 / SyE1an7D4ph
2021-12-06T19:30:59+01:00	INFO	AutoPeering	autopeering/plugin.go:145	Removed offline: 87.78.158.27:14626 / 69xS5EzFTWA
echo: http: panic serving 172.25.0.1:40044: runtime error: invalid memory address or nil pointer dereference
goroutine 716243 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1801 +0xb9
panic({0x176ee20, 0x2d53230})
	/usr/local/go/src/runtime/panic.go:1047 +0x266
github.com/iotaledger/goshimmer/packages/ledgerstate.(*Transaction).Essence(...)
	/goshimmer/packages/ledgerstate/transaction.go:348
github.com/iotaledger/goshimmer/packages/tangle.(*LedgerState).SnapshotUTXO(0xc0003ffcb0)
	/goshimmer/packages/tangle/ledgerstate.go:207 +0x43e
github.com/iotaledger/goshimmer/plugins/webapi/snapshot.DumpCurrentLedger({0x230fed8, 0xc0a2e9c380})
	/goshimmer/plugins/webapi/snapshot/plugin.go:52 +0x50
github.com/labstack/echo.(*Echo).Add.func1({0x230fed8, 0xc0a2e9c380})
	/go/pkg/mod/github.com/labstack/echo@v3.3.10+incompatible/echo.go:490 +0x6d
github.com/labstack/echo/middleware.CORSWithConfig.func1.1({0x230fed8, 0xc0a2e9c380})
	/go/pkg/mod/github.com/labstack/echo@v3.3.10+incompatible/middleware/cors.go:117 +0x578
github.com/labstack/echo.(*Echo).ServeHTTP(0xc00041c000, {0x22c04c8, 0xc034e8c000}, 0xc000118700)
	/go/pkg/mod/github.com/labstack/echo@v3.3.10+incompatible/echo.go:593 +0x2ea
net/http.serverHandler.ServeHTTP({0xc0e391b2c0}, {0x22c04c8, 0xc034e8c000}, 0xc000118700)
	/usr/local/go/src/net/http/server.go:2878 +0x43b
net/http.(*conn).serve(0xc03d4bac80, {0x22d2c78, 0xc00e460660})
	/usr/local/go/src/net/http/server.go:1929 +0xb08
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3033 +0x4e8
2021-12-06T19:31:09+01:00	INFO	AutoPeering	autopeering/plugin.go:142	Discovered: 87.78.158.27:14626 / 69xS5EzFTWA
echo: http: panic serving 172.25.0.1:40048: runtime error: invalid memory address or nil pointer dereference
goroutine 716598 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1801 +0xb9
panic({0x176ee20, 0x2d53230})
	/usr/local/go/src/runtime/panic.go:1047 +0x266
github.com/iotaledger/goshimmer/packages/ledgerstate.(*Transaction).Essence(...)
	/goshimmer/packages/ledgerstate/transaction.go:348
github.com/iotaledger/goshimmer/packages/tangle.(*LedgerState).SnapshotUTXO(0xc0003ffcb0)
	/goshimmer/packages/tangle/ledgerstate.go:207 +0x43e
github.com/iotaledger/goshimmer/plugins/webapi/snapshot.DumpCurrentLedger({0x230fed8, 0xc044aa93b0})
	/goshimmer/plugins/webapi/snapshot/plugin.go:52 +0x50
github.com/labstack/echo.(*Echo).Add.func1({0x230fed8, 0xc044aa93b0})
	/go/pkg/mod/github.com/labstack/echo@v3.3.10+incompatible/echo.go:490 +0x6d
github.com/labstack/echo/middleware.CORSWithConfig.func1.1({0x230fed8, 0xc044aa93b0})
	/go/pkg/mod/github.com/labstack/echo@v3.3.10+incompatible/middleware/cors.go:117 +0x578
github.com/labstack/echo.(*Echo).ServeHTTP(0xc00041c000, {0x22c04c8, 0xc000176540}, 0xc000603b00)
	/go/pkg/mod/github.com/labstack/echo@v3.3.10+incompatible/echo.go:593 +0x2ea
net/http.serverHandler.ServeHTTP({0xc0385a55c0}, {0x22c04c8, 0xc000176540}, 0xc000603b00)
	/usr/local/go/src/net/http/server.go:2878 +0x43b
net/http.(*conn).serve(0xc03315e320, {0x22d2c78, 0xc00e460660})
	/usr/local/go/src/net/http/server.go:1929 +0xb08
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3033 +0x4e8
2021-12-06T19:31:20+01:00	INFO	AutoPeering	autopeering/plugin.go:142	Discovered: 80.138.241.125:14646 / MPskpm5wSHU
2021-12-06T19:31:30+01:00	INFO	AutoPeering	autopeering/plugin.go:142	Discovered: 167.86.122.61:14646 / SyE1an7D4ph
```

**Comment by karimodm** [comment]
What I think happens there is the following: the snaphost gets requested with curl. The snapshot takes some time to prepare; and by the time it is written to the socket, curl already aborted because of a read timeout. So we have to fix this on two fronts: 1) goshimmer should detected the socket as closed and handle the error correctly without panicing 2) curl's timeout should be made longer in the Ansible snapshotter role so we actually wait long enough to obtain it and upload it.

**Comment by karimodm** [comment]
This seems to be a bug in the storage: the ledgerstate copy returned by `func (u *UTXODAG) Transactions()` returns `nil` pointer Transactions.
