### ISSUE TITLE
Bug: problem with selecting orphans floating around after search

### ISSUE THREAD

**Issue by daria305** [iotaledger/goshimmer#1989]
When we select some single tx/msgs floating around after search the info window does not show up and they stay selected forever even if an other message is selected.
![image](https://user-images.githubusercontent.com/44535712/151128222-9a99a67b-873d-440b-9b94-3d11097af01f.png)

**Comment by acha-bill** [comment]
Was just about to open this issue :)

Also, it throws an error:
```
Uncaught TypeError: node.links is not iterable
    at dfsIterator (:8061/static/js/main.chunk.js:3958:29)
    at selectMessage (:8061/static/js/main.chunk.js:3806:3)
    at TangleStore.selectMsg (:8061/static/js/main.chunk.js:5471:89)
    at HTMLDivElement.<anonymous> (:8061/static/js/main.chunk.js:5788:14)
    at executeAction (:8061/static/js/vendors~main.chunk.js:74346:15)
    at HTMLDivElement.tangleOnClick (:8061/static/js/vendors~main.chunk.js:74329:12)
```
