### ISSUE TITLE
panic: zmq4: could not exchange greetings

### ISSUE THREAD

**Issue by yillkid** [iotaledger/goshimmer#54]
#### Log section:
```
...skipping...
Jul 26 16:29:09 node0 ubuntu[10661]: [  OK  ] Starting Plugin: Spammer ... done
Jul 26 16:29:09 node0 ubuntu[10661]: [  OK  ] Starting background workers ...
Jul 26 16:29:09 node0 ubuntu[10661]: [  OK  ] WebAPI: Starting Web Server ... done
Jul 26 16:29:09 node0 ubuntu[10661]: [ INFO ] Auto Peering: Starting UDP Server (port 14626) ...
Jul 26 16:29:09 node0 ubuntu[10661]: [ INFO ] Auto Peering: Starting TCP Server (port 14626) ...
Jul 26 16:29:09 node0 ubuntu[10661]: [  OK  ] Gossip: Starting Send Queue Dispatcher ... done
Jul 26 16:29:09 node0 ubuntu[10661]: [ INFO ] Auto Peering: Starting Chosen Neighbor Processor ...
Jul 26 16:29:09 node0 ubuntu[10661]: [  OK  ] Auto Peering: Starting Chosen Neighbor Processor ... done
Jul 26 16:29:09 node0 ubuntu[10661]: [  OK  ] Bundle Processor: Starting Bundle Processor ... done
Jul 26 16:29:09 node0 ubuntu[10661]: [  OK  ] Tangle: Starting Solidifier ... done
Jul 26 16:29:09 node0 ubuntu[10661]: [  OK  ] Gossip: Starting TCP Server (port 14666) ... done
Jul 26 16:29:09 node0 ubuntu[10661]: [ INFO ] Auto Peering: Starting Ping Processor ...
Jul 26 16:29:09 node0 ubuntu[10661]: [  OK  ] Auto Peering: Starting Ping Processor ... done
Jul 26 16:29:09 node0 ubuntu[10661]: [  OK  ] Auto Peering: Starting UDP Server (port 14626) ... done
Jul 26 16:29:09 node0 ubuntu[10661]: [  OK  ] Bundle Processor: Starting Value Bundle Processor ... done
Jul 26 16:29:09 node0 ubuntu[10661]: [  OK  ] ZeroMQ: Starting ZeroMQ Publisher (port 5556) ... done
Jul 26 16:29:09 node0 ubuntu[10661]: [  OK  ] Auto Peering: Starting TCP Server (port 14626) ... done
Jul 26 16:31:41 node0 ubuntu[10661]: [ INFO ] Auto Peering: new peer discovered: 164.68.105.123 / 5b839bea06dbb61ef9b4f7a43526e4245a17bbe0
Jul 26 16:31:41 node0 ubuntu[10661]: [ INFO ] Auto Peering: new peer discovered: 10.233.96.0 / bf8cfc87e0f38a5793baf645d6e7be1a810fabed
Jul 26 16:31:41 node0 ubuntu[10661]: [ INFO ] Auto Peering: new peer discovered: 10.233.96.0 / 52d77c9901d04c6bce76fe421e2a6fdc58fafddf
Jul 26 16:31:47 node0 ubuntu[10661]: [ INFO ] Auto Peering: new peer discovered: 164.68.105.123 / 73c26ca1810666ca6b70947dc9a9324b7198a4ec
Jul 26 16:31:47 node0 ubuntu[10661]: [ INFO ] Auto Peering: new peer discovered: 164.68.105.123 / 95030b3150264a0a248765c998ec86ea0df94a20
Jul 26 16:31:52 node0 ubuntu[10661]: [ INFO ] Auto Peering: new peer discovered: 164.68.105.123 / 824737ce28e5b00c6ad8c68279c92a914c8546e4
Jul 26 16:34:17 node0 ubuntu[10661]: [ INFO ] Auto Peering: new peer discovered: 164.68.105.123 / 4913107a290feb2eaaaa630951100eff33962a1b
Jul 26 16:34:17 node0 ubuntu[10661]: [ INFO ] Auto Peering: new peer discovered: 164.68.105.123 / ada88939f9f69fcec39725a59b1599643e5db9ad
Jul 26 16:34:17 node0 ubuntu[10661]: [ INFO ] Auto Peering: new peer discovered: 10.233.96.0 / f2c380146010798b2a737713954c81561de3b781
Jul 26 16:36:54 node0 ubuntu[10661]: [ INFO ] Auto Peering: new peer discovered: 164.68.105.123 / 58fc322713f263bb26f420df97d239a1efde1fe7
Jul 26 16:37:10 node0 ubuntu[10661]: [ INFO ] Auto Peering: new peer discovered: 164.68.105.123 / 232c523ceb5bda6b7291f8b34736e1119c3f30b8
Jul 26 16:44:21 node0 ubuntu[10661]: [  OK  ] Gossip: new neighbor added ee012d6051385e021a212d5100ab5a8866a0b265@79.143.187.45:14666
Jul 26 16:51:57 node0 ubuntu[10661]: panic: zmq4: could not exchange greetings: zmq4: could not recv greeting: read tcp 140.116.82.61:5556->67.205.184.67:32766: read: c
Jul 26 16:51:57 node0 ubuntu[10661]: goroutine 384 [running]:
Jul 26 16:51:57 node0 ubuntu[10661]: github.com/go-zeromq/zmq4.(*socket).accept(0xc001be4000)
Jul 26 16:51:57 node0 ubuntu[10661]:         /home/ubuntu/go/pkg/mod/github.com/go-zeromq/zmq4@v0.4.0/socket.go:178 +0x1b0
Jul 26 16:51:57 node0 ubuntu[10661]: created by github.com/go-zeromq/zmq4.(*socket).Listen
Jul 26 16:51:57 node0 ubuntu[10661]:         /home/ubuntu/go/pkg/mod/github.com/go-zeromq/zmq4@v0.4.0/socket.go:157 +0x17b
Jul 26 16:51:57 node0 systemd[1]: goshimmer.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 26 16:51:57 node0 systemd[1]: goshimmer.service: Failed with result 'exit-code'.
```

**Comment by Wollac** [comment]
Can you please provide more information about how to reproduce this issue?
For example: What zmq client is used? Is another zmq server running? When was the client started? ...

**Comment by StefanoCore** [comment]
> Can you please provide more information about how to reproduce this issue?
> For example: What zmq client is used? Is another zmq server running? When was the client started? ...

I'm facing a similar situation and i can replicate it, even if the error i get it's slightly different:

![image](https://user-images.githubusercontent.com/10340922/62160086-6f072300-b313-11e9-9c9d-6974c657b28c.png)

Here the steps which i use to reproduce the error:
1. I start the node on my VPS (UFW deactivated)
2. From my local PC, i hit the ZMQ port with Telnet `telnet my-node.com 5556`
3. Without disconnecting the telnet connection, i close the terminal
4. The node crashes with the error above

**Comment by Wollac** [comment]
@StefanoCore 
When connecting to the ZMQ port with Telnet your are in fact violating the ZMQ handshake protocol, which will not happen with a proper ZMQ client. However, I agree, it would be much nicer if an error is thrown here in the ZMQ library instead of a panic.
I'll forward this issue to the go-zeromq library...

**Comment by StefanoCore** [comment]
@Wollac I completely agree with you. I reported it because it could be a potential point of attack for all the nodes (with a really easy effort from the attacker side).

**Comment by StefanoCore** [comment]
@Wollac Don't know if it can be useful. My node crashed again on the same issue but it wasn't done by me. Don't know if anyone else tried in a different way to attack my ZMQ channel.

![image](https://user-images.githubusercontent.com/10340922/62425785-88c2b480-b6dd-11e9-8003-4db76d6a8936.png)

**Comment by dspautz** [comment]
same problem here
