### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by jkrvivian** [iotaledger/goshimmer#68]
I got this error on the latest commit of master branch without spamming, running on Ubuntu 16.04.
This error occurs randomly, the first time took 54mins and the second time took around 18hours to this error.

**Log Section**:
```
[  OK  ] Gossip: new neighbor added 50788800f711a484767c9a1689dd82f2603f5084@79.143.187.45:14666
[  OK  ] Gossip: existing neighbor removed 4e5148d767be66c982cdf3f5b5f381499e959410@164.68.105.123:14666
[  OK  ] Gossip: new neighbor added e261ba4dde35b9c774ff5f51b3d01fdf64f32bae@76.95.216.109:14666
[  OK  ] Gossip: existing neighbor removed e261ba4dde35b9c774ff5f51b3d01fdf64f32bae@76.95.216.109:14666
[  OK  ] Gossip: new neighbor added 5f0cb3d524562bdbe2d9d1e86c59a96942a7efe3@164.68.105.123:14666
[  OK  ] Gossip: existing neighbor removed 5f0cb3d524562bdbe2d9d1e86c59a96942a7efe3@164.68.105.123:14666
[  OK  ] Gossip: new neighbor added 5f0cb3d524562bdbe2d9d1e86c59a96942a7efe3@164.68.105.123:14666
[  OK  ] Gossip: existing neighbor removed 5f0cb3d524562bdbe2d9d1e86c59a96942a7efe3@164.68.105.123:14666
[  OK  ] Gossip: new neighbor added 40ed2c282b6b0711ffda46785ddb514080f2c697@116.203.90.249:14666
[  OK  ] Gossip: existing neighbor removed db2f7ae39a1f7485675ef0ebb47e01114bb75b91@91.250.99.217:14666
[  OK  ] Gossip: existing neighbor updated 2032a502995b75ae46640790348c3614336fb83f@10.233.96.0:14666
[  OK  ] Gossip: existing neighbor removed 40ed2c282b6b0711ffda46785ddb514080f2c697@116.203.90.249:14666
[  OK  ] Gossip: new neighbor added a4de5e47853d41200e1c9931999c057c19c41930@207.180.244.109:14666
[  OK  ] Gossip: existing neighbor updated fe83c5f719bea60e9ff471ae98fb489b12826545@164.68.105.123:14666
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x835b86]

goroutine 241542 [running]:
github.com/iotaledger/goshimmer/packages/network.(*ManagedConnection).Close(0x0, 0xabd839, 0xc)
        /home/jkrvivian/IOTA/goshimmer/packages/network/managed_connection.go:71 +0x26
github.com/iotaledger/goshimmer/plugins/autopeering/protocol.processIncomingResponse(0xc0011556e0, 0xc000113ab0)
        /home/jkrvivian/IOTA/goshimmer/plugins/autopeering/protocol/incoming_response_processor.go:20 +0xb7
created by github.com/iotaledger/goshimmer/plugins/autopeering/protocol.createIncomingResponseProcessor.func1
        /home/jkrvivian/IOTA/goshimmer/plugins/autopeering/protocol/incoming_response_processor.go:13 +0x48
jkrvivian:goshimmer $ 
```

**Comment by hmoog** [comment]
Fixed by 9eaead509e7f1b49b0018ba58f38b7a9c12f2cde
