### ISSUE TITLE
Index out of range

### ISSUE THREAD

**Issue by capossele** [iotaledger/goshimmer#899]
The result of metrics.measureCPUUsage() is used without check

**Comment by lzpap** [comment]
@capossele can you provide more info on this? `metrics.measureCPUUsage()` triggers an event with a single `float64` value.

**Comment by capossele** [comment]
```
Dec 20 05:33:31 antipirinas goshimmer[562269]: panic: runtime error: index out of range [0] with length 0
Dec 20 05:33:31 antipirinas goshimmer[562269]: goroutine 814531 [running]:
Dec 20 05:33:31 antipirinas goshimmer[562269]: github.com/iotaledger/goshimmer/plugins/metrics.measureCPUUsage()
Dec 20 05:33:31 antipirinas goshimmer[562269]:         /lunar_build/goshimmer-0.3.4/plugins/metrics/process.go:28 +0x11c
Dec 20 05:33:31 antipirinas goshimmer[562269]: github.com/iotaledger/goshimmer/plugins/metrics.run.func1.1()
Dec 20 05:33:31 antipirinas goshimmer[562269]:         /lunar_build/goshimmer-0.3.4/plugins/metrics/plugin.go:67 +0x25
Dec 20 05:33:31 antipirinas goshimmer[562269]: github.com/iotaledger/hive.go/timeutil.Ticker(0x1adf270, 0x3b9aca00, 0xc02d396000)
Dec 20 05:33:31 antipirinas goshimmer[562269]:         /lunar_build/goshimmer-0.3.4/goshimmer_go_dependencies/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20201203130604-bd82d648670e/timeutil/ticker.go:18 +0x85
Dec 20 05:33:31 antipirinas goshimmer[562269]: github.com/iotaledger/goshimmer/plugins/metrics.run.func1(0xc02d396000)
Dec 20 05:33:31 antipirinas goshimmer[562269]:         /lunar_build/goshimmer-0.3.4/plugins/metrics/plugin.go:66 +0x1e5
Dec 20 05:33:31 antipirinas goshimmer[562269]: github.com/iotaledger/hive.go/daemon.(*OrderedDaemon).runBackgroundWorker.func1(0x1adf278, 0xc02d382ee0, 0xc02d17d490)
Dec 20 05:33:31 antipirinas goshimmer[562269]:         /lunar_build/goshimmer-0.3.4/goshimmer_go_dependencies/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20201203130604-bd82d648670e/daemon/daemon.go:130 +0x34
Dec 20 05:33:31 antipirinas goshimmer[562269]: created by github.com/iotaledger/hive.go/daemon.(*OrderedDaemon).runBackgroundWorker
Dec 20 05:33:31 antipirinas goshimmer[562269]:         /lunar_build/goshimmer-0.3.4/goshimmer_go_dependencies/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20201203130604-bd82d648670e/daemon/daemon.go:129 +0xe7
Dec 20 05:33:31 antipirinas systemd[1]: goshimmer.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 20 05:33:31 antipirinas systemd[1]: goshimmer.service: Failed with result 'exit-code'.
```
